#!/bin/bash

# Recompilacao do arquivo gatewaymysql e syncmysql do projeto mtd
# wget hvip.com.br/mtd/paulo/rebuild.sh --user=mtd --password=lserf2018mtd -O /root/rebuild.sh
# chmod 100 /root/rebuild.sh
# /root/rebuild.sh 1

#####################################################################################################
### SETUP Passwords: ################################################################################
#####################################################################################################
#Urlftp="hvip.com.br"
#User="mtd"
#Passwd="lserf2018mtd"
bitbucketUser="97thiagobs@gmail.com"
bitbucketPw="thiago123"

### END SETUP ###

Varx=$1
if [ $# -lt 1 ]; then
   echo "rebuild.sh: O número do HARDWARE do MTD deve ser informado na linha de comando!"
   echo "exemplo: /root/rebuild.sh 1"
   exit 1
fi

### Atualizando o proprio rebuild.sh
#wget $Urlftp/mtd/paulo/rebuild.sh --user=$User --password=$Passwd -O /root/rebuild.shx
Arquivox="rebuild.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/a8b772af2c25ec764adae5c64552272a61f2e2a0/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/rebuild.shx -o /root/rebuild.sh

/etc/init.d/cron stop
/usr/bin/killall -9 gatewaymysql
/usr/bin/killall -9 syncmysql


#####################################################################################################
### Preparando Crontab: #############################################################################
#####################################################################################################

echo "# DO NOT EDIT THIS FILE - edit the master and reinstall." > /var/spool/cron/crontabs/root
echo "# (/tmp/crontab.bJH62W/crontab installed on Wed Nov 28 18:08:01 2018)" >> /var/spool/cron/crontabs/root
echo "# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)" >> /var/spool/cron/crontabs/root
echo "# m h  dom mon dow   command" >> /var/spool/cron/crontabs/root
echo "#Gateway Mysql:" >> /var/spool/cron/crontabs/root
echo "*/1 * * * * /root/gatewaymysql.sh" >> /var/spool/cron/crontabs/root
echo "#Sync Mysql:" >> /var/spool/cron/crontabs/root
echo "*/1 * * * * /root/syncmysql.sh" >> /var/spool/cron/crontabs/root

#####################################################################################################
### Diretorios: #####################################################################################
#####################################################################################################

cd /root
rm -rf /mtd
mkdir /mtd >/dev/null 2>&1
mkdir /mtd/audf >/dev/null 2>&1
mkdir /mtd/terf >/dev/null 2>&1
mkdir /mtd/hrff >/dev/null 2>&1
mkdir /mtd/emcf >/dev/null 2>&1
mkdir /mtd/audtmp >/dev/null 2>&1
mkdir /mtd/tertmp >/dev/null 2>&1
mkdir /mtd/hrftmp >/dev/null 2>&1
mkdir /mtd/emctmp >/dev/null 2>&1
mkdir /mtd/dados >/dev/null 2>&1

#####################################################################################################
### Dev Scripts ...: ################################################################################
#####################################################################################################
echo "#define HARDWARE $1" > /root/hardware.h
chmod 644 /root/hardware.h

#wget $Urlftp/mtd/paulo/autologin.sh --user=$User --password=$Passwd -O /root/autologin.shx > /tmp/wgetrebuild 2>&1
Arquivox="autologin.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/autologin.shx -o /root/autologin.sh

#wget $Urlftp/mtd/paulo/100leituras.sh --user=$User --password=$Passwd -O /root/100leituras.shx > /tmp/wgetrebuild 2>&1
Arquivox="100leituras.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/100leituras.shx -o /root/100leituras.sh
/root/100leituras.sh > /dev/null 2>&1 &

#wget $Urlftp/mtd/paulo/audios.sh --user=$User --password=$Passwd -O /root/audios.shx > /tmp/wgetrebuild 2>&1
Arquivox="audios.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/audios.shx -o /root/audios.sh

#wget $Urlftp/mtd/paulo/termis.sh --user=$User --password=$Passwd -O /root/termis.shx > /tmp/wgetrebuild 2>&1
Arquivox="termis.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/termis.shx -o /root/termis.sh

#wget $Urlftp/mtd/paulo/hckrfs.sh --user=$User --password=$Passwd -O /root/hckrfs.shx > /tmp/wgetrebuild 2>&1
Arquivox="hckrfs.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/hckrfs.shx -o /root/hckrfs.sh

#wget $Urlftp/mtd/paulo/emcmis.sh --user=$User --password=$Passwd -O /root/emcmis.shx > /tmp/wgetrebuild 2>&1
Arquivox="emcmis.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/emcmis.shx -o /root/emcmis.sh

#wget $Urlftp/mtd/paulo/gatewaymysql.sh --user=$User --password=$Passwd -O /root/gatewaymysql.shx > /tmp/wgetrebuild 2>&1
Arquivox="gatewaymysql.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/gatewaymysql.shx -o /root/gatewaymysql.sh

#wget $Urlftp/mtd/paulo/syncmysql.sh --user=$User --password=$Passwd -O /root/syncmysql.shx > /tmp/wgetrebuild 2>&1
Arquivox="syncmysql.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/syncmysql.shx -o /root/syncmysql.sh

#wget $Urlftp/mtd/paulo/gkill.sh --user=$User --password=$Passwd -O /root/gkill.shx > /tmp/wgetrebuild 2>&1
Arquivox="gkill.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/gkill.shx -o /root/gkill.sh

#wget $Urlftp/mtd/paulo/insere.sh --user=$User --password=$Passwd -O /root/insere.shx > /tmp/wgetrebuild 2>&1
Arquivox="insere.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/insere.shx -o /root/insere.sh

#wget $Urlftp/mtd/paulo/select.sh --user=$User --password=$Passwd -O /root/select.shx > /tmp/wgetrebuild 2>&1
Arquivox="select.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget--user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/select.shx -o /root/select.sh

#wget $Urlftp/mtd/paulo/syncfile.sh --user=$User --password=$Passwd -O /root/syncfile.shx > /tmp/wgetrebuild 2>&1
Arquivox="syncfile.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/syncfile.shx -o /root/syncfile.sh

#wget $Urlftp/mtd/paulo/truncate.sh --user=$User --password=$Passwd -O /root/truncate.shx > /tmp/wgetrebuild 2>&1
Arquivox="truncate.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/truncate.shx -o /root/truncate.sh
/root/truncate.sh > /dev/null 2>&1 &

#wget $Urlftp/mtd/paulo/wifi.sh --user=$User --password=$Passwd -O /root/wifi.shx > /tmp/wgetrebuild 2>&1
Arquivox="wifi.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/wifi.shx -o /root/wifi.sh
cp /root/wifi.sh /mtd/wifi.sh

#wget $Urlftp/mtd/paulo/executeStream.sh --user=$User --password=$Passwd -O /root/executeStream.shx > /tmp/wgetrebuild 2>&1
Arquivox="executeStream.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/executeStream.shx -o /root/executeStream.sh

#wget $Urlftp/mtd/paulo/cloudmtd.sh --user=$User --password=$Passwd -O /root/cloudmtd.shx > /tmp/wgetrebuild 2>&1
Arquivox="cloudmtd.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/cloudmtd.shx -o /bin/cloudmtd

#wget $Urlftp/mtd/paulo/ipcfg.sh --user=$User --password=$Passwd -O /root/ipcfg.shx > /tmp/wgetrebuild 2>&1
Arquivox="ipcfg.sh"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox""x"" > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
shc -f /root/ipcfg.shx -o /root/ipcfg.sh

#wget $Urlftp/mtd/paulo/termico.zip --user=$User --password=$Passwd -O /root/termico.zip > /tmp/wgetrebuild 2>&1
Arquivox="termico.zip"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 644 /root/termico.zip

#wget $Urlftp/mtd/paulo/hackrf.zip --user=$User --password=$Passwd -O /root/hackrf.zip > /tmp/wgetrebuild 2>&1
Arquivox="hackrf.zip"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 644 /root/hackrf.zip

#wget $Urlftp/mtd/paulo/emcemi.zip --user=$User --password=$Passwd -O /root/emcemi.zip > /tmp/wgetrebuild 2>&1
Arquivox="emcemi.zip"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 644 /root/emcemi.zip

#####################################################################################################
### Downlaod dos arquivos fontes ...: ###############################################################
#####################################################################################################

### Módulos programa principal do mtd e syncronismo: (Paulo)
# File: cat /root/gatewaymysql.c
#Dirx="/root/"
#Filex="gatewaymysql.c"
#Fullx=$Dirx$Filex
#/usr/bin/wget $Urlftp/mtd/paulo/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="gatewaymysql.c"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done

# File: cat /root/syncmysql.c
#Dirx="/root/"
#Filex="syncmysql.c"
#Fullx=$Dirx$Filex
#/usr/bin/wget $Urlftp/mtd/paulo/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="syncmysql.c"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done

# File: cat /root/conexaobd.h
#Dirx="/root/"
#Filex="conexaobd.h"
#Fullx=$Dirx$Filex
#/usr/bin/wget $Urlftp/mtd/paulo/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="conexaobd.h"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/cbe7c361519157ddf2cd7dde3a1e9de61b886214/paulo/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done

### Sensor de Audio: (Mathias):
# File: cat /mtd/coef.csv
#Dirx="/mtd/"
#Filex="coef.csv"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/mathias/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="coef.csv"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/fbe11025ed7c58d045c09a08e91c928ac8903327/mathias/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/audioProcessing_vAdaptiveFilter.m
#Dirx="/mtd/"
#Filex="audioProcessing_vAdaptiveFilter_final.m"
#Filey="audioProcessing_vAdaptiveFilter.m"
#Fullx=$Dirx$Filey
#wget $Urlftp/mtd/mathias/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="audioProcessing_vAdaptiveFilter_final.m"
Arquivoy="audioProcessing_vAdaptiveFilter.m"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/fbe11025ed7c58d045c09a08e91c928ac8903327/mathias/$Arquivox -O /mtd/$Arquivoy > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivoy

# File: cat /mtd/main_final_audio.c
#Dirx="/mtd/"
#Filex="main_final_audio.c"
#Filey="audios.c"
#Fullx=$Dirx$Filey
#wget $Urlftp/mtd/mathias/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="main_final_audio.c"
Arquivoy="audios.c"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/fbe11025ed7c58d045c09a08e91c928ac8903327/mathias/$Arquivox -O /mtd/$Arquivoy > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivoy

### Sensor Térmico: (Rick)
# File: /root/arquivos.zip
# Arquivo com > 400Mb ... cheksum verification before download ...
#Dirx="/root/"
#Filex="arquivos.zip.md5"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/rick/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="arquivos.zip.md5"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/rick/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 644 /root/$Arquivox
cd /root
md5sum --status --check arquivos.zip.md5 > /dev/null 2>&1
Resposta=$?
rm -rf $Fullx 
if [ $Resposta -eq 0 ]
then
   echo "Checksum MD5SUM OK - [$Resposta]"
else
   echo "Checksum MD5SUM NOK - [$Resposta] - Download ..."
   #Dirx="/root/"
   #Filex="arquivos.zip"
   #Fullx=$Dirx$Filex
   #wget $Urlftp/mtd/rick/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
   Arquivox="arquivos.zip"
   Resultadox=""
   Contadorx=1
   while [ "$Resultadox" == "" ]
         do
           echo "Download Arquivo: [$Arquivox] [Tamanho > 400Mb / aproximadamente 5 minutos para Download - Aguarde! ]- wget"
           Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/21a007f249434a80887f0e4651e15a3401b45c66/rick/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
           Resultadox=`eval $Comandox`
           Comandox="cat /tmp/wgetrebuild | grep saved"
           Resultadox=`eval $Comandox`
           echo "Tentativa ==> [$Contadorx] [$Resultadox]"
           let Contadorx=$Contadorx+1;
           if [ $Contadorx -gt 30 ]; then
              Resultadox="***Erro no Download***"
              echo "[$Resultadox]"
           fi
         done
   md5sum /root/arquivos.zip > /tmp/arquivos.zip.md5
   /usr/bin/wput -v -B -u --disable-tls /tmp/arquivos.zip.md5 ftp://hvip:rogerioluz3079@hvip.com.br/www/mtd/rick/arquivos.zip.md5
   chmod 644 /root/$Arquivox
fi

# File: cat /mtd/pylepton_capture
#Dirx="/mtd/"
#Filex="pylepton_capture"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/rick/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="pylepton_capture"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/250b79d80f06ff659d215828702255da5eacafc9/rick/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/sensor_termico_final.c
#Dirx="/mtd/"
#Filex="sensor_termico_final.c"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/rick/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="sensor_termico_final.c"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/250b79d80f06ff659d215828702255da5eacafc9/rick/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox
#cloudmtd download /rick/sensor_termico_final.c /mtd/sensor_termico_final.c

#Sensor HackRF: (Felipe)
# File: cat /mtd/felipe/compare.cpp
#Dirx="/mtd/felipe/"
#Filex="compare.cpp"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="compare.cpp"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/felipe/import.h
#Dirx="/mtd/felipe/"
#Filex="import.h"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="import.h"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/analysis.h
#Dirx="/mtd/felipe/"
#Filex="analysis.h"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="analysis.h"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /root/dadosmedidores.zip
#Dirx="/root/"
#Filex="dadosmedidores.zip"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="dadosmedidores.zip"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /root/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 644 /root/$Arquivox

#Sensor Emi: (Felipe)
# File: cat /mtd/felipe/compare_e.cpp
#Dirx="/mtd/felipe/"
#Filex="compare_e.cpp"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="compare_e.cpp"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/felipe/import_e.h
#Dirx="/mtd/"
#Filex="import_e.h"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="import_e.h"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

# File: cat /mtd/analysis_e.h
#Dirx="/mtd/felipe/"
#Filex="analysis_e.h"
#Fullx=$Dirx$Filex
#wget $Urlftp/mtd/felipe/$Filex --http-user=$User --http-password=$Passwd -O $Fullx
Arquivox="analysis_e.h"
Resultadox=""
Contadorx=1
while [ "$Resultadox" == "" ]
      do
        echo "Download Arquivo: [$Arquivox] - wget"
        Comandox="wget --user=$bitbucketUser --password=$bitbucketPw https://bitbucket.org/generatech/mtdrepositorio/raw/de48df5fbade93637ff18031945ce7c529241161/felipe/$Arquivox -O /mtd/$Arquivox > /tmp/wgetrebuild 2>&1"
        Resultadox=`eval $Comandox`
        Comandox="cat /tmp/wgetrebuild | grep saved"
        Resultadox=`eval $Comandox`
        echo "Tentativa ==> [$Contadorx] [$Resultadox]"
        let Contadorx=$Contadorx+1;
        if [ $Contadorx -gt 30 ]; then
           Resultadox="***Erro no Download***"
           echo "[$Resultadox]"
        fi
      done
chmod 755 /mtd/$Arquivox

#####################################################################################################
### Instalar o pylepton: ############################################################################
#####################################################################################################

cd /mtd
git clone https://github.com/generagit/pylepton.git
cd /mtd/pylepton
python setup.py install

#####################################################################################################
### Compilando o Programa ...: ######################################################################
#####################################################################################################
rm -rf /root/gatewaymysql
rm -rf /root/syncymysql
cd /root
#compilando programa principal do mtd e syncronismo:
gcc -o2 gatewaymysql.c -o gatewaymysql -lmysqlclient
gcc -o2 syncmysql.c -o syncmysql -lmysqlclient
#compilando programa principal do modulo de audio:
gcc /mtd/audios.c -o /mtd/audios
#compilando programa principal do modulo termico:
unzip -o /root/arquivos.zip -d /mtd
chmod +x /mtd/teste_*
chmod +x /mtd/modifica_nomes
chmod +x /mtd/calibration
gcc /mtd/sensor_termico_final.c -o /mtd/termis -lwiringPi 
rm /mtd/sensor_termico_final.c
#compilando programa principal do modulo HackRf:
unzip -o /root/dadosmedidores.zip -d /mtd/dados/
g++ /mtd/compare.cpp -o /mtd/hckrfs -lpthread
#compilando programa principal do modulo EMI:
g++ /mtd/compare_e.cpp -o /mtd/emcmis -lpthread
rm -rf /mtd/*.h
rm -rf /mtd/*.cpp
### Limpando diretorio /root
rm -rf /root/*.shx
rm -rf /root/*.h
rm -rf /root/*.c
rm -rf /root/*.md5
/etc/init.d/cron start
#End of Script